---
- hosts: localhost
  gather_facts: false
  # All data is sourced from group_vars/all.yml

  # Basically generate, with a state:
  #   ssh config
  #   inventory file
  # Really want to get this to run each time you provison the VM
  # then you don't have to worry about creating stuff, it just runs

  # To get rid of the state part, we need to do a jinja template, I think
  # Basically just want to run the vagrant provisioner to just do this
  # and take care of the ssh file and inventory if we delete stuff from all.yml

  # Still need to create the inventory file, as other plays outside of this project
  # will reference that file

  tasks:
    - name: Print the tests 
      debug:
        var: host_list

    - name: Add hosts for vagrant into sshconfg
      blockinfile:
        path: "{{ssh_config}}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
         
        block: | 
          Host {{item.name}} *.test.local
            hostname {{item.ip}}
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            User {{ssh_user}}
            LogLevel ERROR  
        
        state: "{{item.state}}"

      with_items:
        - "{{host_list}}"

    - name: Ensure "fav=lemonade is in section "[drinks]" in specified file
      ini_file:
        path: "{{host_file}}"
        section: "{{item.group}}"
        option: "{{item.name}} ansible_ssh_host"
        value: "{{item.ip}}"
      with_items: "{{ host_list }}"

      tags:
        - hosts


    - name: Add IP address of all hosts to all hosts needs -K on cli
      become: true
      lineinfile:
        dest: /etc/hosts
        line: "{{item.name}} ansible_host={{item.ip}}"
        state: present
      with_items: "{{ host_list }}"
  
