---
- hosts: localhost
  gather_facts: false
  # All data is sourced from group_vars/all.yml

  # Basically generate, with a state:
  #   ssh config
  #   inventory file

  tasks:
    - name: Print the tests 
      debug:
        var: host_list

    - name: Add hosts for vagrant into sshconfg
      blockinfile:
        path: "{{ssh_config}}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
         
        block: | 
          Host {{item.name}} *.test.local
            hostname {{item.ip}}
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            User {{ssh_user}}
            LogLevel ERROR  
        
        state: "{{item.state}}"

      with_items:
        - "{{host_list}}"

    - name: Add hosts to inventory
      lineinfile:
        path: "{{host_file}}"
        line: "{{item.name}} ansible_ssh_host={{item.ip}}"
        state: "{{item.state}}"
      with_items:
        - "{{host_list}}"