---
- hosts: localhost
  gather_facts: false

  vars:
    update: false

# To Do
# Add a destroy task, which cleans up all the config
# and get rid of the "Status" section in the all.yml file

  tasks:      
    - name: Check inventory paths exist and create if not
      file:
        path: "{{ host_path }}"
        state: directory

      tags:
        - host_path

    - name: Check that the host file exists
      stat:
        path: "{{ host_file }}"
      register: stat_result
      tags: host_file

    - name: Create the file, if it doesnt exist already
      file:
        path: "{{ host_file }}"
        state: touch
      when: stat_result.stat.exists == False  
      tags: host_file
 
    # This bit is not working very well..
    # If the file gets out of order, delete it and it will get generated again
    # - name: add group to inventory file
    #   lineinfile:
    #     path: "{{host_file}}"
    #     regexp: "{{item.group}}"
    #     line: "[{{item.group}}]"
    #     state: "{{item.state}}"
    #     firstmatch: yes
    #   with_items: "{{ host_list }}"
    #   run_once: true
    #   tags: group

    # - name: add host to inventory file
    #   lineinfile:
    #     path: "{{host_file}}"
    #     regexp: "{{item.name}}"
    #     line: "{{item.name}} ansible_ssh_host={{item.ip}}"
    #     insertafter: "{{item.group}}"
    #     state: "{{item.state}}"
    #   with_items: "{{ host_list }}"
    #   tags: inv

    - name: Add hosts for vagrant into sshconfg
      blockinfile:
        path: "{{ssh_config}}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
         
        block: | 
          Host {{item.name}} *.test.local
            hostname {{item.ip}}
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            User {{ssh_user}}
            LogLevel ERROR  
        
        state: "{{item.state}}"

      with_items:
        - "{{host_list}}"

      tags: sshconfg
  

    - name: Add the Vagrant Boxes
      shell: 'vagrant box add {{item}} --insecure --provider virtualbox'
   
      register: result

      with_items:
        - "{{box_list}}"

      failed_when: "'A name is required' in result.stderr"

      when: update

      tags: box_add




