---
- hosts: localhost
  gather_facts: false

  vars:
    debug: "false"

  # All data is sourced from group_vars/all.yml

  # Basically generate, with a state:
  #   ssh config
  #   inventory file
  #   /etc/hosts

  # Really want to get this to run each time you provison the VM
  # then you don't have to worry about creating stuff, it just runs
  # Tested on 2.4 and 2.5 2.6

  # Need to make some path checking at the start, as this keeps failing
  # Also exit if not run as root checking
  # Update the readme to how you run it..
  # Like make sure to have ansible installed, then run the playbook then vagrant up
  # Also had to download the boxes first the it was good

  tasks:
    - name: Print the tests 
      debug:
        var: host_list
      when: (debug == 'true')
      tags:
        - debug
        
    # - name: This playbook must run as root to edit the hosts file
    #   local_action: command whoami
    #   register: username_on_the_host

    - debug: var=username_on_the_host

    - name: Add hosts for vagrant into sshconfg
      blockinfile:
        path: "{{ssh_config}}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
         
        block: | 
          Host {{item.name}} *.test.local
            hostname {{item.ip}}
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            User {{ssh_user}}
            LogLevel ERROR  
        
        state: "{{item.state}}"

      with_items:
        - "{{host_list}}"

      tags:
        - sshconfg

    # This looks like it is now fixed
    - name: add group to inventory file
      lineinfile:
        path: "{{host_file}}"
        regexp: "{{item.group}}"
        line: "[{{item.group}}]"
        state: "{{item.state}}"
        firstmatch: yes
      with_items: "{{ host_list }}"
      tags:
        - group

    - name: add host to inventory file
      lineinfile:
        path: "{{host_file}}"
        regexp: "{{item.name}}"
        line: "{{item.name}} ansible_ssh_host={{item.ip}}"
        insertafter: "{{item.group}}"
        state: "{{item.state}}"
      with_items: "{{ host_list }}"
      tags:
        - inv

    - name: Add IP address of all hosts to all hosts needs -K on cli
      become: true
      lineinfile:
        dest: /etc/hosts
        line: "{{item.ip}} {{item.name}}"
        state: "{{item.state}}"
      with_items: "{{ host_list }}"

      tags:
        - hosts
  
