---
- hosts: localhost
  gather_facts: false

  vars:
    debug: "false"
  
  # All data is sourced from group_vars/all.yml

  # Basically generate, with a state:
  #   ssh config
  #   inventory file
  #   /etc/hosts

  # Really want to get this to run each time you provison the VM
  # then you don't have to worry about creating stuff, it just runs

  tasks:
    - name: Print the tests 
      debug:
        var: host_list

      when: (debug == 'true')

      tags:
        - debug

    - name: Add hosts for vagrant into sshconfg
      blockinfile:
        path: "{{ssh_config}}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
         
        block: | 
          Host {{item.name}} *.test.local
            hostname {{item.ip}}
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            User {{ssh_user}}
            LogLevel ERROR  
        
        state: "{{item.state}}"

      with_items:
        - "{{host_list}}"

      tags:
        - sshconfg

    - name: Generate the inventory file
      ini_file:
        path: "{{host_file}}"
        section: "{{item.group}}"
        option: "{{item.name}} ansible_ssh_host"
        value: "{{item.ip}}"
      with_items: "{{ host_list }}"

      tags:
        - inventory

    - name: Add IP address of all hosts to all hosts needs -K on cli
      become: true
      lineinfile:
        dest: /etc/hosts
        line: "{{item.ip}} {{item.name}}"
        state: present
      with_items: "{{ host_list }}"

      tags:
        - hosts
  
